$primary = {{ primary.strip }}
$secondary = {{ secondary.strip }}

$background = {{ background.strip }}
$surface = {{ surface.strip }}
$border = {{ border.strip }}

$foreground = {{ foreground.strip }}
$muted = {{ muted.strip }}

$success = {{ success.strip }}
$warning = {{ warning.strip }}
$error = {{ error.strip }}
