foreground         {{ foreground }}
background         {{ background }}
cursor             {{ primary.darken(0.2) }}

active_tab_foreground     {{ surface }}
active_tab_background     {{ foreground }}
inactive_tab_foreground   {{ foreground }}
inactive_tab_background   {{ surface }}

active_border_color   {{ foreground }}
inactive_border_color {{ background }}
bell_border_color     {{ warning }}
